name = "alchemical"
main = "src/worker.js"
compatibility_date = "2025-02-04"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "jutsumoji"
database_id = "51604989-07b2-43bd-8bb6-68680d9622dc"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "99f274107ed043dcbe27881f46ee17bc"

[[kv_namespaces]]
binding = "BOT_SESSIONS"
id = "b14b9bfdb25e42008596447e4d931472"
preview_id = "<ID_OF_PREVIEW_BOT_SESSIONS_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT>"

[[kv_namespaces]]
binding = "ARENA_KV"
id = "b14b9bfdb25e42008596447e4d931472"
preview_id = "<ID_OF_PREVIEW_ARENA_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT>"
